version: "3"
services:
  db:
    image: mariadb:10
    #volumes:  # TODO: do we want it?
      #- ./docker/mysql/data/:/var/lib/mysql/
    networks:
      - AMP
    environment:
      - MYSQL_ROOT_PASSWORD=docker
    ports:
      - "3306:3306"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - AMP
    volumes:
      - ./docker/redis/data/:/data
    ports:
      - "6379:6379"
networks:
  AMP:
